### ISSUE TITLE
Column names not aligning?

### ISSUE THREAD

**Issue by mnr006** [Bucknell-Biol364/RNASeqProject#5]
https://github.com/Bucknell-Biol364/RNASeqProject/blob/a0562c5e6bc7fe3f27cb017905ee9c4fab428602/DEBrowser/DEBrowser.R#L59

Hi @KField-Bucknell 
I didn't realize that this document gave how to instructions of combining data so I had attempted it on my own the Friday before break, and just saw all the code today for table generation. I was able to get through most of it and editing it to fit my data. However, when I get to the actual column comparison I have a "Name" column in my count tables that is in disagreement with the column names of the metadata sample (or at least I'm assuming that's the issue based on a deep R investigation). Also for some reason I couldn't cite an issue within my own document- so hopefully you can still access it...

**Comment by KField-Bucknell** [comment]
Megan-
Were you able to figure this out? I looked at your repo and I found the metadata.tsv and other tables. The only problem that I see is that the sample names have not been trimmed properly using the gsub lines. You will need to customize those so that you get the correct names.
Prof. Field
